import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { matchesApi } from '../api/matches'
import type { Match } from '../types'
import Navbar from '../components/UI/Navbar'
import { colors, gradients, radius } from '../styles/theme'
import {
  Brain, Lightning, Swords, Mic, Rewind, BarChart,
  Trophy, Target, TrendUp, Calendar, Play, Eye,
} from '../components/UI/Icons'

const FEATURES = [
  {
    Icon: Brain, title: 'Pre-Match Strategy',
    desc: 'Build your Playing XI, lock opening pairs, nominate powerplay and death bowlers before the toss.',
    color: colors.purple,
  },
  {
    Icon: Lightning, title: 'Live Decision Windows',
    desc: '10-second windows open during bowling changes, field setups, and key match moments. Every call scored instantly.',
    color: colors.orange,
  },
  {
    Icon: Swords, title: 'Head-to-Head Challenges',
    desc: 'Challenge a friend to a tactical duel — or an AI coach auto-joins if no one accepts in 30 seconds.',
    color: colors.green,
  },
  {
    Icon: Mic, title: 'AI Commentator',
    desc: 'Harsha Bhogle–style over summaries generated by OpenAI gpt-4o-mini, with live browser TTS.',
    color: colors.blue,
  },
  {
    Icon: Rewind, title: 'Tactical Replay',
    desc: 'Rewind any over after the match. Try different field placements or bowling changes and see alternate scores.',
    color: colors.yellow,
  },
  {
    Icon: BarChart, title: 'Coach Report Card',
    desc: 'Personalised post-match rating: Rookie → Elite Coach. Share as a downloadable PNG.',
    color: colors.red,
  },
]

const SCORING = [
  { Icon: Target, label: 'Captain Alignment', pts: '40 pts', color: colors.orange, desc: 'How closely your call matched what the actual captain did' },
  { Icon: TrendUp, label: 'Historical Merit', pts: '40 pts', color: colors.purple, desc: 'How effective this decision has been in similar IPL situations' },
  { Icon: Brain, label: 'Tactical Rules', pts: '20 pts', color: colors.green, desc: 'Smart cricket intelligence — slip for pace, spin mid-overs, etc.' },
]

export default function Home() {
  const [matches, setMatches] = useState<Match[]>([])
  const [loading, setLoading] = useState(true)
  const navigate = useNavigate()

  useEffect(() => {
    matchesApi.list().then(r => setMatches(r.data)).finally(() => setLoading(false))
  }, [])

  return (
    <div style={{ minHeight: '100vh', background: gradients.page }}>
      <Navbar />

      {/* ── Hero ── */}
      <div style={s.hero}>
        <div style={s.heroChip}>
          <Calendar size={12} color={colors.orange} />
          IPL 2026 Season
        </div>
        <h1 style={s.heroTitle}>
          Be the Coach.<br />
          <span style={s.heroGradient}>Beat the Captain.</span>
        </h1>
        <p style={s.heroSub}>
          Make real-time tactical decisions during live IPL simulations.
          Earn points, get OpenAI analysis on every call, and prove you're
          the sharpest cricket mind in the country.
        </p>
        <div style={s.heroStats}>
          {[
            { Icon: Target, label: '5 Matches' },
            { Icon: Lightning, label: '4 Decision Types' },
            { Icon: Brain, label: 'OpenAI Powered' },
            { Icon: Trophy, label: 'Live Leaderboard' },
          ].map(({ Icon, label }) => (
            <div key={label} style={s.statChip}>
              <Icon size={13} color={colors.orange} />
              <span style={s.statLabel}>{label}</span>
            </div>
          ))}
        </div>
      </div>

      {/* ── Scoring System ── */}
      <div style={s.section}>
        <div style={s.sectionHeader}>
          <h2 style={s.sectionTitle}>How Points Work</h2>
          <span style={s.sectionBadge}>100 pts per decision</span>
        </div>
        <div style={s.scoringGrid}>
          {SCORING.map(({ Icon, label, pts, color, desc }) => (
            <div key={label} style={{ ...s.scoringCard, borderColor: `${color}22` }}>
              <div style={{ ...s.scoringIconWrap, background: `${color}14`, border: `1px solid ${color}28` }}>
                <Icon size={22} color={color} />
              </div>
              <div style={s.scoringPts}>{pts}</div>
              <div style={s.scoringLabel}>{label}</div>
              <div style={s.scoringDesc}>{desc}</div>
            </div>
          ))}
        </div>
        <div style={s.scoringNote}>
          <Eye size={13} color={colors.textFaint} />
          After every decision, OpenAI provides a 2–3 sentence tactical breakdown explaining the captain's logic and what historical data says.
        </div>
      </div>

      {/* ── Features ── */}
      <div style={s.section}>
        <div style={s.sectionHeader}>
          <h2 style={s.sectionTitle}>Platform Features</h2>
        </div>
        <div style={s.featureGrid}>
          {FEATURES.map(({ Icon, title, desc, color }) => (
            <div key={title} style={{ ...s.featureCard, borderColor: `${color}20` }}>
              <div style={{ ...s.featureIconWrap, background: `${color}12`, border: `1px solid ${color}22` }}>
                <Icon size={20} color={color} />
              </div>
              <div>
                <div style={s.featureTitle}>{title}</div>
                <div style={s.featureDesc}>{desc}</div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ── Matches ── */}
      <div style={s.section}>
        <div style={s.sectionHeader}>
          <h2 style={s.sectionTitle}>Matches</h2>
          <div style={s.liveDot} />
          <span style={s.liveText}>Live updates</span>
        </div>

        {loading ? (
          <div style={s.matchGrid}>
            {[1, 2, 3].map(i => <div key={i} style={s.skeleton} />)}
          </div>
        ) : (
          <div style={s.matchGrid}>
            {matches.map(m => (
              <MatchCard key={m.id} match={m} onEnter={() => navigate(`/match/${m.id}`)} />
            ))}
          </div>
        )}
      </div>
    </div>
  )
}

function MatchCard({ match, onEnter }: { match: Match; onEnter: () => void }) {
  const isLive = match.status === 'live'
  const isUpcoming = match.status === 'upcoming'

  const statusColor = isLive ? colors.green : isUpcoming ? colors.blue : colors.textFaint
  const statusBg = isLive ? 'rgba(34,197,94,0.12)' : isUpcoming ? 'rgba(59,130,246,0.1)' : 'rgba(255,255,255,0.05)'
  const statusBorder = isLive ? 'rgba(34,197,94,0.25)' : isUpcoming ? 'rgba(59,130,246,0.2)' : 'rgba(255,255,255,0.07)'
  const statusLabel = isLive ? 'LIVE' : isUpcoming ? 'UPCOMING' : 'COMPLETED'

  return (
    <div style={{ ...s.matchCard, ...(isLive ? s.matchCardLive : {}) }}>
      {/* Status + venue */}
      <div style={s.matchTop}>
        <span style={{ ...s.badge, background: statusBg, color: statusColor, border: `1px solid ${statusBorder}` }}>
          {isLive && <span style={s.pulseDot} />}
          {statusLabel}
        </span>
        <span style={s.venue}>{match.venue}</span>
      </div>

      {/* Teams */}
      <div style={s.teamsRow}>
        <div style={s.teamBlock}>
          <div style={s.teamAvatar}>{match.team_a[0]}</div>
          <span style={s.teamName}>{match.team_a}</span>
          {match.status !== 'upcoming' && (
            <span style={s.teamScore}>{match.team_a_score}/{match.team_a_wickets}</span>
          )}
        </div>
        <div style={s.vsBlock}>
          <span style={s.vs}>vs</span>
          {isLive && (
            <div style={s.liveChip}>
              <Activity size={10} color={colors.green} />
              <span>LIVE</span>
            </div>
          )}
        </div>
        <div style={{ ...s.teamBlock, alignItems: 'flex-end' }}>
          <div style={s.teamAvatar}>{match.team_b[0]}</div>
          <span style={s.teamName}>{match.team_b}</span>
          {match.status !== 'upcoming' && (
            <span style={s.teamScore}>{match.team_b_score}/{match.team_b_wickets}</span>
          )}
        </div>
      </div>

      {/* CTA */}
      <button style={{ ...s.enterBtn, ...(isLive ? s.btnLive : isUpcoming ? s.btnUpcoming : s.btnDone) }} onClick={onEnter}>
        {isLive
          ? <><Play size={13} color="#fff" /> Join Live</>
          : isUpcoming
            ? <><Target size={13} color="#fff" /> Enter Match</>
            : <><BarChart size={13} color={colors.textMuted} /> View Summary</>
        }
      </button>
    </div>
  )
}

// Tiny local import of Activity icon
function Activity({ size = 10, color = 'currentColor' }: { size?: number; color?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill="none"
      stroke={color} strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
    </svg>
  )
}

const s: Record<string, React.CSSProperties> = {
  hero: { textAlign: 'center', padding: '80px 24px 48px', maxWidth: 740, margin: '0 auto' },
  heroChip: {
    display: 'inline-flex', alignItems: 'center', gap: 6,
    background: 'rgba(249,115,22,0.1)', border: '1px solid rgba(249,115,22,0.22)',
    color: colors.orange, fontSize: 12, fontWeight: 700,
    padding: '6px 16px', borderRadius: 20, marginBottom: 24, letterSpacing: 0.5,
  },
  heroTitle: { fontSize: 'clamp(36px,6vw,58px)', fontWeight: 900, lineHeight: 1.1, color: colors.text, marginBottom: 20 },
  heroGradient: { background: 'linear-gradient(90deg,#f97316,#f59e0b)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent' },
  heroSub: { fontSize: 17, color: colors.textMuted, lineHeight: 1.7, maxWidth: 560, margin: '0 auto 32px' },
  heroStats: { display: 'flex', gap: 10, justifyContent: 'center', flexWrap: 'wrap' },
  statChip: {
    display: 'flex', alignItems: 'center', gap: 7,
    background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)',
    borderRadius: 20, padding: '7px 16px', fontSize: 13,
  },
  statLabel: { color: colors.textMuted, fontWeight: 500 },

  section: { maxWidth: 1200, margin: '0 auto', padding: '0 24px 60px' },
  sectionHeader: { display: 'flex', alignItems: 'center', gap: 10, marginBottom: 24 },
  sectionTitle: { fontSize: 22, fontWeight: 800, color: colors.text },
  sectionBadge: {
    fontSize: 11, fontWeight: 700,
    background: 'rgba(249,115,22,0.1)', color: colors.orange,
    border: '1px solid rgba(249,115,22,0.2)',
    padding: '3px 10px', borderRadius: 20,
  },
  liveDot: { width: 8, height: 8, borderRadius: '50%', background: colors.green, boxShadow: `0 0 8px ${colors.green}` },
  liveText: { fontSize: 12, color: colors.textFaint },

  scoringGrid: { display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: 16, marginBottom: 16 },
  scoringCard: {
    display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center',
    gap: 10, padding: '28px 20px',
    background: 'rgba(255,255,255,0.025)',
    border: '1px solid', borderRadius: radius.xl,
    backdropFilter: 'blur(10px)',
  },
  scoringIconWrap: { width: 52, height: 52, borderRadius: 16, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  scoringPts: { fontSize: 28, fontWeight: 900, color: colors.text, lineHeight: 1 },
  scoringLabel: { fontSize: 14, fontWeight: 700, color: colors.text },
  scoringDesc: { fontSize: 12, color: colors.textMuted, lineHeight: 1.6 },
  scoringNote: {
    display: 'flex', alignItems: 'flex-start', gap: 8,
    background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.06)',
    borderRadius: radius.md, padding: '12px 16px',
    fontSize: 13, color: colors.textFaint, lineHeight: 1.6,
  },

  featureGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(280px,1fr))', gap: 14 },
  featureCard: {
    display: 'flex', alignItems: 'flex-start', gap: 16, padding: '20px',
    background: 'rgba(255,255,255,0.025)', border: '1px solid',
    borderRadius: radius.lg, backdropFilter: 'blur(10px)',
  },
  featureIconWrap: { width: 44, height: 44, borderRadius: 12, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  featureTitle: { fontSize: 14, fontWeight: 700, color: colors.text, marginBottom: 4 },
  featureDesc: { fontSize: 12, color: colors.textMuted, lineHeight: 1.6 },

  matchGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill,minmax(340px,1fr))', gap: 20 },
  skeleton: { height: 200, background: 'rgba(255,255,255,0.04)', borderRadius: radius.lg },

  matchCard: {
    background: 'linear-gradient(135deg,rgba(255,255,255,0.04),rgba(255,255,255,0.02))',
    border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: radius.xl, padding: 24,
    display: 'flex', flexDirection: 'column', gap: 20,
    backdropFilter: 'blur(20px)', transition: 'transform 0.2s, box-shadow 0.2s',
  },
  matchCardLive: {
    border: '1px solid rgba(34,197,94,0.2)',
    boxShadow: '0 0 30px rgba(34,197,94,0.06)',
  },
  matchTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  badge: { fontSize: 11, fontWeight: 800, padding: '4px 10px', borderRadius: 20, display: 'flex', alignItems: 'center', gap: 5, letterSpacing: 0.5 },
  pulseDot: { width: 7, height: 7, borderRadius: '50%', background: colors.green, animation: 'pulse 1s infinite' },
  venue: { fontSize: 11, color: colors.textFaint },
  teamsRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
  teamBlock: { display: 'flex', flexDirection: 'column', gap: 5 },
  teamAvatar: {
    width: 40, height: 40, borderRadius: 12,
    background: 'rgba(249,115,22,0.12)', border: '1px solid rgba(249,115,22,0.18)',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: 15, fontWeight: 800, color: colors.orange,
  },
  teamName: { fontSize: 13, fontWeight: 700, color: colors.text },
  teamScore: { fontSize: 24, fontWeight: 900, color: colors.orange, lineHeight: 1 },
  vsBlock: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 6 },
  vs: { fontSize: 11, color: colors.textFaint, fontWeight: 600 },
  liveChip: {
    display: 'flex', alignItems: 'center', gap: 3,
    background: 'rgba(34,197,94,0.12)', border: '1px solid rgba(34,197,94,0.25)',
    borderRadius: 20, padding: '3px 8px', fontSize: 9, fontWeight: 800, color: colors.green,
  },
  enterBtn: {
    display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7,
    width: '100%', padding: '13px', border: 'none',
    borderRadius: radius.md, fontWeight: 700, cursor: 'pointer', fontSize: 13,
  },
  btnLive: { background: 'linear-gradient(135deg,#22c55e,#16a34a)', color: '#fff', boxShadow: '0 4px 16px rgba(34,197,94,0.25)' },
  btnUpcoming: { background: 'linear-gradient(135deg,#f97316,#ea580c)', color: '#fff', boxShadow: '0 4px 16px rgba(249,115,22,0.25)' },
  btnDone: { background: 'rgba(255,255,255,0.05)', color: colors.textMuted, border: `1px solid rgba(255,255,255,0.08)` },
}
